### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by IanM-CF** [akamai-open/imaging-sample-ui#8]
On Linux, I get this error when using ./run.sh to start the server:

```
        if (cache) cache[base] = base;
                               ^

TypeError: Cannot assign to read only property '/home' of ./
    at Object.realpathSync (fs.js:1442:32)
    at Object.<anonymous> (/home/ec2-user/imaging-sample-ui/OPENwrapper/src/openReq.js:40:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ec2-user/imaging-sample-ui/OPENwrapper/index.js:1:80)
    at Module._compile (module.js:409:26)

```
I get the same error trying to run the code on Windows. I'm using commit 6dab694cabc7cc41f69a967961cc91fd890cee51

**Comment by sivicencio** [comment]
Same error here on Mac OS X 10.11.6.

```
fs.js:1525
        if (cache) cache[base] = base;
                               ^

TypeError: Cannot assign to read only property '/Users' of ./
    at Object.realpathSync (fs.js:1525:32)
    at Object.<anonymous> (/Users/myuser/Documents/code/ripley/imaging-sample-ui/OPENwrapper/src/openReq.js:40:23)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/myuser/Documents/code/ripley/imaging-sample-ui/OPENwrapper/index.js:1:80)
    at Module._compile (module.js:398:26)
```
